[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "windflow-tide"
version = "0.2.0"
description = "Python DSL for WindFlow"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "jinja2>=3.1.0",
]

[tool.setuptools.packages.find]
include = ["windflow_tide*"]
